DROP TABLE IF EXISTS PIEZAS;
DROP TABLE IF EXISTS MENSAJES;
DROP TABLE IF EXISTS USUARIOS;


CREATE TABLE PIEZAS (
						ID_PIEZA 			SMALLINT UNSIGNED   auto_increment PRIMARY KEY NOT NULL,
						NSERIE	 			CHAR(100) 			UNIQUE NOT NULL,
						NOMBRE   			CHAR(100) 			NOT NULL, 
						MARCA	 			CHAR(50)  			NOT NULL, 
						BALDA    			CHAR(2)   			DEFAULT NULL, 
						CAJA     			SMALLINT UNSIGNED   DEFAULT NULL, 
						STOCK    			SMALLINT UNSIGNED	DEFAULT NULL

				)engine=InnoDB;


CREATE TABLE USUARIOS (
						ID_USER  			SMALLINT UNSIGNED	auto_increment PRIMARY KEY NOT NULL, 
						USER	 			CHAR(100)			UNIQUE NOT NULL,
						PASSWD   			TEXT				NOT NULL,
						NIF		 			CHAR(9)				NOT NULL,
						NOMBRE   			CHAR(50)			NOT NULL, 
						TELFN    			CHAR(10)			NOT NULL,
						NIVEL_SEGURIDAD 	TINYINT				NOT NULL,
						ULT_CONEXION		TIMESTAMP 			NULL


				)engine=InnoDB;

CREATE TABLE MENSAJES (
						ID_MENSAJE 			SMALLINT UNSIGNED	auto_increment PRIMARY KEY NOT NULL,
						ID_EMISOR  			SMALLINT UNSIGNED	NOT NULL, 
						ID_RECEPTOR  		SMALLINT UNSIGNED	NOT NULL, 
						TITULO				CHAR(30)			NOT NULL,
						LEIDO				BOOLEAN				DEFAULT 0 NOT NULL,
						TEXTO				TEXT 				NOT NULL,
						FECHA				TIMESTAMP 			DEFAULT CURRENT_TIMESTAMP, 


						CONSTRAINT FK_USUARIOS_MENSAJES1 
							FOREIGN KEY (ID_EMISOR)
									REFERENCES USUARIOS(ID_USER)
									ON DELETE CASCADE ON UPDATE CASCADE,

						CONSTRAINT FK_USUARIOS_MENSAJES2 
							FOREIGN KEY (ID_RECEPTOR) 
									REFERENCES USUARIOS(ID_USER)
									ON DELETE CASCADE ON UPDATE CASCADE, 
				)engine=InnoDB;
